const INPUT: { [key:string]: string } = {
DEMO_0: '^WNE$',
DEMO_1: '^ENWWW(NEEE|SSE(EE|N))$',
DEMO_2: '^ENNWSWW(NEWS|)SSSEEN(WNSE|)EE(SWEN|)NNN$',
DEMO_3: '^ESSWWN(E|NNENN(EESS(WNSE|)SSS|WWWSSSSE(SW|NNNE)))$',
DEMO_4: '^WSSEESWWWNW(S|NENNEEEENN(ESSSSW(NWSW|SSEN)|WSWWN(E|WWS(E|SS))))$',
}

export default INPUT