const INPUT: { [key: string]: string } = {
  DEMO_0: `        ...#
        .#..
        #...
        ....
...#.......#
........#...
..#....#....
..........#.
        ...#....
        .....#..
        .#......
        ......#.

10R5L5R10L4R5L5`,
}

export default INPUT
